{{ if eq .Values.dbSettings.dbProvider "rds"}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-rds-service
  name: postgres-rds-service
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  externalName: {{ .Values.dbSettings.rdsEndpoint }}
  selector:
    app: postgres-rds-service
  type: ExternalName
status:
  loadBalancer: {}
{{ end }}